language: cpp
sudo: false

# Use Linux operating system (OS) unless specified otherwise.
os: linux
dist: trusty

env:
  global:
    - CMAKE_VERSION=3.10.3
    - NINJA_VERSION=1.8.2

# TODO(2018-10-14 by wolters) Add support for Mac OS X and additional compiler
# versions.
matrix:
  include:
  - name: "GCC 7, Debug"
    env:
      - C_COMPILER=gcc-7
      - CXX_COMPILER=g++-7
      - BUILD_TYPE=Debug
    addons: &gcc7
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
  - name: "GCC 7, Release"
    env:
      - C_COMPILER=gcc-7
      - CXX_COMPILER=g++-7
      - BUILD_TYPE=Release
    addons: *gcc7
  - name: "Clang 7, Debug"
    env:
      - C_COMPILER=clang-7.0
      - CXX_COMPILER=clang++-7.0
      - BUILD_TYPE=Debug
    addons: &clang7
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-7
  - name: "Clang 7, Release"
    env:
      - C_COMPILER=clang-7.0
      - CXX_COMPILER=clang++-7.0
      - BUILD_TYPE=Release
    addons: *clang7

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      # Download and install CMake.
      mkdir -p ~/cmake-${CMAKE_VERSION}-x64
      wget --quiet https://cmake.org/files/v${CMAKE_VERSION::-2}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh
      bash cmake-${CMAKE_VERSION}-Linux-x86_64.sh --prefix="${HOME}/cmake-${CMAKE_VERSION}-x64" --exclude-subdir --skip-license

      # Download and install Ninja.
      wget --quiet https://github.com/ninja-build/ninja/releases/download/v${NINJA_VERSION}/ninja-linux.zip
      unzip ninja-linux.zip -d ~/ninja-${NINJA_VERSION}
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew upgrade cmake
    fi

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export PATH=~/cmake-${CMAKE_VERSION}-x64/bin:~/ninja-${NINJA_VERSION}:$PATH
    fi

script:
  # Configure & Generate the project.
  # TODO(2018-10-14 by wolters) Currently the undocumented CMake options -H and
  # -B are used. This can be changed with the coming CMake release v3.11.
  - cmake -G "Ninja" -DCMAKE_CXX_COMPILER:STRING="${CXX_COMPILER}" -DCMAKE_C_COMPILER:STRING="${C_COMPILER}" -DCMAKE_BUILD_TYPE:STRING="${BUILD_TYPE}" -H. -B_build
  # Build the project.
  - cmake --build _build
  # Test the project.
  - cmake --build _build --target test

notifications:
  email:
    on_success: never
    on_failure: never
