language: cpp
sudo: false

# Use Linux operating system (OS) unless specified otherwise.
os: linux
dist: trusty

env:
  global:
    - CMAKE_VERSION=3.10.3
    - NINJA_VERSION=1.8.2

# TODO(2018-10-14 by wolters) Add support for Mac OS X.
matrix:
  include:
  - name: "OS: linux (trusty), Compiler:gcc (default), Build Type: Debug"
    compiler: gcc
    env:
      - C_COMPILER=gcc
      - CXX_COMPILER=g++
      - BUILD_TYPE=Debug
  include:
  - name: "OS: linux (trusty), Compiler:gcc (default), Build Type: Release"
    compiler: gcc
    env:
      - C_COMPILER=gcc
      - CXX_COMPILER=g++
      - BUILD_TYPE=Release
  include:
  - name: "OS: linux (trusty), Compiler:gcc 8, Build Type: Debug"
    compiler: gcc
    env:
      - C_COMPILER=gcc-8
      - CXX_COMPILER=g++-8
      - BUILD_TYPE=Debug
    addons: &gcc8
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
  - name: "OS: linux (trusty), Compiler:gcc 8, Build Type: Release"
    compiler: gcc
    env:
      - C_COMPILER=gcc-8
      - CXX_COMPILER=g++-8
      - BUILD_TYPE=Release
    addons: *gcc8
  - name: "OS: linux (trusty), Compiler:gcc 7, Build Type: Debug"
    compiler: gcc
    env:
      - C_COMPILER=gcc-7
      - CXX_COMPILER=g++-7
      - BUILD_TYPE=Debug
    addons: &gcc7
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
  - name: "OS: linux (trusty), Compiler:gcc 7, Build Type: Release"
    compiler: gcc
    env:
      - C_COMPILER=gcc-7
      - CXX_COMPILER=g++-7
      - BUILD_TYPE=Release
    addons: *gcc7
  - name: "OS: linux (trusty), Compiler:gcc 6, Build Type: Debug"
    compiler: gcc
    env:
      - C_COMPILER=gcc-6
      - CXX_COMPILER=g++-6
      - BUILD_TYPE=Debug
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
  - name: "OS: linux (trusty), Compiler:gcc 6, Build Type: Release"
    compiler: gcc
    env:
      - C_COMPILER=gcc-6
      - CXX_COMPILER=g++-6
      - BUILD_TYPE=Release
    addons: *gcc6
  - name: "OS: linux (trusty), Compiler:gcc 5, Build Type: Debug"
    compiler: gcc
    env:
      - C_COMPILER=gcc-5
      - CXX_COMPILER=g++-5
      - BUILD_TYPE=Debug
    addons: &gcc5
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
  - name: "OS: linux (trusty), Compiler:gcc 5, Build Type: Release"
    compiler: gcc
    env:
      - C_COMPILER=gcc-5
      - CXX_COMPILER=g++-5
      - BUILD_TYPE=Release
    addons: *gcc5
  - name: "OS: linux (trusty), Compiler:clang (default), Build Type: Debug"
    compiler: clang
    env:
      - C_COMPILER=clang
      - CXX_COMPILER=clang++
      - BUILD_TYPE=Debug
  - name: "OS: linux (trusty), Compiler:clang (default), Build Type: Release"
    compiler: clang
    env:
      - C_COMPILER=clang
      - CXX_COMPILER=clang++
      - BUILD_TYPE=Release
  - name: "OS: linux (trusty), Compiler:clang 7, Build Type: Debug"
    compiler: clang
    env:
      - C_COMPILER=clang-7
      - CXX_COMPILER=clang++-7
      - BUILD_TYPE=Debug
    addons: &clang7
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-7
        packages:
          - clang-7
  - name: "OS: linux (trusty), Compiler:clang 7, Build Type: Release"
    compiler: clang
    env:
      - C_COMPILER=clang-7
      - CXX_COMPILER=clang++-7
      - BUILD_TYPE=Release
    addons: *clang7
  - name: "OS: linux (trusty), Compiler:clang 6, Build Type: Debug"
    compiler: clang
    env:
      - C_COMPILER=clang-6.0
      - CXX_COMPILER=clang++-6.0
      - BUILD_TYPE=Debug
    addons: &clang6
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
  - name: "OS: linux (trusty), Compiler:clang 6, Build Type: Release"
    compiler: clang
    env:
      - C_COMPILER=clang-6.0
      - CXX_COMPILER=clang++-6.0
      - BUILD_TYPE=Release
    addons: *clang6
  - name: "OS: linux (trusty), Compiler:clang 5, Build Type: Debug"
    compiler: clang
    env:
      - C_COMPILER=clang-5.0
      - CXX_COMPILER=clang++-5.0
      - BUILD_TYPE=Debug
    addons: &clang5
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
  - name: "OS: linux (trusty), Compiler:clang 4, Build Type: Release"
    compiler: clang
    env:
      - C_COMPILER=clang-4.0
      - CXX_COMPILER=clang++-4.0
      - BUILD_TYPE=Release
    addons: *clang4
  - name: "OS: linux (trusty), Compiler:clang 4, Build Type: Debug"
    compiler: clang
    env:
      - C_COMPILER=clang-4.0
      - CXX_COMPILER=clang++-4.0
      - BUILD_TYPE=Debug
    addons: &clang4
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
  - name: "OS: linux (trusty), Compiler:clang 4, Build Type: Release"
    compiler: clang
    env:
      - C_COMPILER=clang-4.0
      - CXX_COMPILER=clang++-4.0
      - BUILD_TYPE=Release
    addons: *clang4
  - name: "OS: xcode10, Compiler: clang (default), Build Type: Debug"
    os: osx
    osx_image: xcode10
    compiler: clang
    env:
      - C_COMPILER=clang
      - CXX_COMPILER=clang++
      - BUILD_TYPE=Debug
  - name: "OS: xcode10, Compiler: clang (default), Build Type: Release"
    os: osx
    osx_image: xcode10
    compiler: clang
    env:
      - C_COMPILER=clang
      - CXX_COMPILER=clang++
      - BUILD_TYPE=Release
  - name: "OS: xcode9, Compiler: clang (default), Build Type: Debug"
    os: osx
    osx_image: xcode9
    compiler: clang
    env:
      - C_COMPILER=clang
      - CXX_COMPILER=clang++
      - BUILD_TYPE=Debug
  - name: "OS: xcode9, Compiler: clang (default), Build Type: Release"
    os: osx
    osx_image: xcode9
    compiler: clang
    env:
      - C_COMPILER=clang
      - CXX_COMPILER=clang++
      - BUILD_TYPE=Release
  - name: "OS: xcode8, Compiler: clang (default), Build Type: Debug"
    os: osx
    osx_image: xcode8
    compiler: clang
    env:
      - C_COMPILER=clang
      - CXX_COMPILER=clang++
      - BUILD_TYPE=Debug
  - name: "OS: xcode8, Compiler: clang (default), Build Type: Release"
    os: osx
    osx_image: xcode8
    compiler: clang
    env:
      - C_COMPILER=clang
      - CXX_COMPILER=clang++
      - BUILD_TYPE=Release

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      # Download and install CMake.
      mkdir -p ~/cmake-${CMAKE_VERSION}-x64
      wget --quiet https://cmake.org/files/v${CMAKE_VERSION::-2}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh
      bash cmake-${CMAKE_VERSION}-Linux-x86_64.sh --prefix="${HOME}/cmake-${CMAKE_VERSION}-x64" --exclude-subdir --skip-license

      # Download and install Ninja.
      wget --quiet https://github.com/ninja-build/ninja/releases/download/v${NINJA_VERSION}/ninja-linux.zip
      unzip ninja-linux.zip -d ~/ninja-${NINJA_VERSION}
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew upgrade cmake
    fi

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export PATH=~/cmake-${CMAKE_VERSION}-x64/bin:~/ninja-${NINJA_VERSION}:$PATH
    fi

script:
  # Configure & Generate the project.
  # TODO(2018-10-14 by wolters) Currently the undocumented CMake options -H and
  # -B are used. This can be changed with the coming CMake release v3.11.
  - cmake -G "Ninja" -DCMAKE_CXX_COMPILER:STRING="${CXX_COMPILER}" -DCMAKE_C_COMPILER:STRING="${C_COMPILER}" -DCMAKE_BUILD_TYPE:STRING="${BUILD_TYPE}" -H. -B_build
  # Build the project.
  - cmake --build _build
  # Test the project.
  - cmake --build _build --target test

notifications:
  email:
    on_success: never
    on_failure: never
